### ISSUE TITLE
put snapcast app to f-droid

### ISSUE THREAD

**Issue by christf** [christf/snapcastc#10]
and thus obsolete the advertisement ridden version from the play store.

**Comment by christf** [comment]
It was discussed on IRC whether the app actually needs to be there, since there already is a module for fhem: 
```
defmod SNAPCAST Snapcast <serverIP>
```

**Comment by herrwusel** [comment]
What about non fhem users?

**Comment by christf** [comment]
On Mon, Mar 04, 2019 at 03:16:28PM +0000, herrwusel wrote:
>What about non fhem users?
They will need a solution as well. In any case, I am not convinced any 
more that the solution is this very app. It might be openhab or 
something entirely different.

I would like to hear from non-fhem users what fits their needs best.


-- 
()  ascii ribbon campaign - against html e-mail
/\  against proprietary attachments

**Comment by herrwusel** [comment]
I'm relying only on the app so far, since home assistant's [component](https://www.home-assistant.io/components/media_player.snapcast/) is not really [working](https://github.com/badaix/snapcast/issues/308#issuecomment-413042803).

**Comment by christf** [comment]
ok. In any case, at the moment the app will not display the clients just yet, while I am already able to control volume and mute status of clients using the api with curl / fhem.

Also the api itself is a little clunky but I would support it if that meant a benefit on the reusability front for the app. Is it the best option though? If so, why?

**Comment by herrwusel** [comment]
I was wrong: home assistant seems to be working fine with the new UI. I can control snapcast completely now so I don't need an app.

![peek 2019-03-06 08-47](https://user-images.githubusercontent.com/8242787/53864457-d03cfb80-3fec-11e9-90c8-6f9f7f4e280f.gif)

**Comment by palitu** [comment]
can you share your config for using the snapcast compnent?  Mine looks nothing like that!

cheers,

**Comment by herrwusel** [comment]
@palitu I use this custom card: https://github.com/kalkih/mini-media-player

You need to set up everything else in the card configuration.

**Comment by palitu** [comment]
sweet - thanks.
can you post or send me the config that you used to get that?


cheers,

**Comment by herrwusel** [comment]
Sure:
```yaml
entities:
  - entity: media_player.snapcast_group...
    group: true
    hide:
      power: true
      volume: true
    info: short
    source: icon
    type: 'custom:mini-media-player'
  - entity: media_player.snapcast_client...
    group: true
    hide:
      controls: true
    type: 'custom:mini-media-player'
  - entity: media_player.snapcast_client...
    group: true
    hide:
      controls: true
    type: 'custom:mini-media-player'
  - entity: media_player.snapcast_client...
    group: true
    hide:
      controls: true
    type: 'custom:mini-media-player
[...]
type: entities
```
I followed one example of the github's readme I linked.
